azure/worker/__init__.py
azure/worker/aio_compat.py
azure/worker/dispatcher.py
azure/worker/tests/functions/async_return_str/function.json
azure/worker/tests/functions/async_return_str/main.py
azure/worker/tests/functions/host.json
azure/worker/tests/test_functions.py

The gRPC dispatcher is now async and async/await functions are now supported (see the `tests/functions/async_return_str` function)

Make everything async

---

azure/worker/dispatcher.py
azure/worker/protos/__init__.py
azure/worker/tests/broken_functions/inout_param/function.json
azure/worker/tests/broken_functions/inout_param/main.py
azure/worker/tests/broken_functions/return_param_in/function.json
azure/worker/tests/broken_functions/return_param_in/main.py
azure/worker/tests/functions/no_return/function.json
azure/worker/tests/functions/no_return/main.py
azure/worker/tests/test_broken_functions.py
azure/worker/tests/test_functions.py
azure/worker/tests/test_mockhost.py
azure/worker/testutils.py

cc @asavaritayal @christopheranderson

prohibit "inout" bindings; ensure functions without "$return" work; don't crash on unsupported messages

---

azure/worker/dispatcher.py
azure/worker/loader.py
azure/worker/tests/broken_functions/import_error/function.json
azure/worker/tests/broken_functions/import_error/main.py
azure/worker/tests/broken_functions/module_not_found_error/function.json
azure/worker/tests/broken_functions/module_not_found_error/main.py
azure/worker/tests/http_functions/ping/README.md
azure/worker/tests/http_functions/ping/function.json
azure/worker/tests/http_functions/ping/main.py
azure/worker/tests/load_functions/host.json
azure/worker/tests/load_functions/ping/README.md
azure/worker/tests/load_functions/ping/function.json
azure/worker/tests/load_functions/ping/main.py
azure/worker/tests/load_functions/relimport/function.json
azure/worker/tests/load_functions/relimport/main.py
azure/worker/tests/load_functions/simple/function.json
azure/worker/tests/load_functions/simple/main.py
azure/worker/tests/load_functions/subdir/function.json
azure/worker/tests/load_functions/subdir/sub/main.py
azure/worker/tests/test_broken_functions.py
azure/worker/tests/test_http_functions.py
azure/worker/tests/test_loader.py
azure/worker/testutils.py

Function modules are now loaded into the special `__azure__` namespace
package to prevent any possible name collisions with non-function
modules.  Additionally, this makes it possible to avoid polluting
`sys.modules` too much.
The loaded module structure is as follows:
```
__azure__.
func1.
func1mod
func2.
func1mod
...
```
Closes: #26

Load function modules into a reserved namespace package

---

azure/worker/dispatcher.py
azure/worker/functions.py
azure/worker/type_converters.py
azure/worker/type_impl.py
azure/worker/type_meta.py
tests/broken_functions/invalid_out_anno/function.json
tests/broken_functions/invalid_out_anno/main.py
tests/http_functions/return_out/function.json
tests/http_functions/return_out/main.py
tests/load_functions/relimport/function.json
tests/load_functions/simple/function.json
tests/load_functions/subdir/function.json
tests/test_broken_functions.py
tests/test_http_functions.py
tests/test_mock_http_functions.py
tests/test_mock_timer_functions.py
tests/test_types.py
tests/timer_functions/return_pastdue/function.json
tests/timer_functions/return_pastdue/main.py

* Group type decoder, encoder, and validator functions in simple
"Converter" classes.
* Drop support for "string", "int", "bytes", "double", and "json"
binding types.  They were never supported directly by Azure
Functions and were added by mistake.
* Add an "Out[HtttResponse]" test.

Encapsulate type conversion and validation logic in classes.

---

azure/functions/__init__.py
azure/functions/_abc.py
azure/worker/testutils.py
azure/worker/type_converters.py
azure/worker/type_impl.py
azure/worker/type_meta.py
tests/blob_functions/get_blob_bytes/function.json
tests/blob_functions/get_blob_bytes/main.py
tests/blob_functions/get_blob_filelike/function.json
tests/blob_functions/get_blob_filelike/main.py
tests/blob_functions/get_blob_return/function.json
tests/blob_functions/get_blob_return/main.py
tests/blob_functions/get_blob_str/function.json
tests/blob_functions/get_blob_str/main.py
tests/blob_functions/host.json
tests/blob_functions/ping/README.md
tests/blob_functions/ping/function.json
tests/blob_functions/ping/main.py
tests/blob_functions/put_blob_bytes/function.json
tests/blob_functions/put_blob_bytes/main.py
tests/blob_functions/put_blob_filelike/function.json
tests/blob_functions/put_blob_filelike/main.py
tests/blob_functions/put_blob_return/function.json
tests/blob_functions/put_blob_return/main.py
tests/blob_functions/put_blob_str/function.json
tests/blob_functions/put_blob_str/main.py
tests/test_blob_functions.py

Input bindings are always passed as an `InputStream` object which
implements `BufferedIOBase` and is a read-only non-seekable stream.
Output parameters can be strings, bytes, or file-like objects.

Initial support for Blob binding

---

azure/worker/bindings/meta.py
azure/worker/bindings/queue.py
tests/test_types.py

Trigger metadata fields are now decoded and validated more rigorously.

Tighten validation for trigger metadata fields

---

azure/worker/testutils.py

Having a required script-root argument makes the tool easier to use, as
it no longer defaults to a tests dir.
See also issue #68.

Require script-root arg for `python -m testutils`.

---

azure/worker/bindings/blob.py
azure/worker/bindings/http.py
azure/worker/bindings/meta.py
azure/worker/bindings/queue.py
azure/worker/bindings/timer.py
azure/worker/dispatcher.py
azure/worker/functions.py

This allows to implement custom type encoding/decoding logic
depending on parameter annotatition type.
Closes issue #67.

Pass Python type to type converters.

---

azure/worker/dispatcher.py
azure/worker/functions.py
tests/blob_functions/ping/main.py
tests/http_functions/no_return_returns/function.json
tests/http_functions/no_return_returns/main.py
tests/http_functions/ping/main.py
tests/load_functions/ping/main.py
tests/queue_functions/ping/main.py
tests/test_http_functions.py

Raise an error if function w/o a $return binding returns a non-None.

---

azure/worker/bindings/blob.py
azure/worker/bindings/meta.py
azure/worker/testutils.py
tests/blob_functions/blob_trigger/function.json
tests/blob_functions/blob_trigger/main.py
tests/blob_functions/get_blob_triggered/function.json
tests/blob_functions/get_blob_triggered/main.py
tests/blob_functions/put_blob_trigger/function.json
tests/blob_functions/put_blob_trigger/main.py
tests/test_blob_functions.py
tests/test_types.py

When declared as a BlobTrigger, the InputStream now exposes the `name`,
`length` and `uri` properties.

Add support for BlobTrigger metadata

---

azure/worker/bindings/__init__.py
azure/worker/bindings/blob.py
azure/worker/bindings/http.py
azure/worker/bindings/meta.py
azure/worker/bindings/queue.py
azure/worker/bindings/timer.py
azure/worker/functions.py

Input and output bindings have different requirements for the type
annotation.  Input bindings are usually passed as a specific
`azure.functions` type, whereas the output type may vary.
This corrects converters that implement both In and Out interfaces.

Validate type annotation separately for input and output bindings

---

azure/functions/_abc.py
azure/functions/_queue.py
azure/worker/bindings/queue.py
tests/queue_functions/queue_trigger/main.py
tests/test_queue_functions.py

This is to synchronize with the nomenclature in Azure Python SDK
Issue #92.

Rename QueueMessage.next_visible_time to time_next_visible

---

azure/functions/_abc.py
docs/index.rst

While at it, fix the default Python source file name to
`__init__.py`
Issue #94.

Document InputStream properties

---

azure/functions_worker/bindings/__init__.py
azure/functions_worker/bindings/meta.py
azure/functions_worker/bindings/servicebus.py
azure/functions_worker/testutils.py
setup.py
tests/servicebus_functions/get_servicebus_triggered/__init__.py
tests/servicebus_functions/get_servicebus_triggered/function.json
tests/servicebus_functions/host.json
tests/servicebus_functions/ping/README.md
tests/servicebus_functions/ping/function.json
tests/servicebus_functions/ping/main.py
tests/servicebus_functions/put_message/__init__.py
tests/servicebus_functions/put_message/function.json
tests/servicebus_functions/put_message_return/__init__.py
tests/servicebus_functions/put_message_return/function.json
tests/servicebus_functions/servicebus_trigger/__init__.py
tests/servicebus_functions/servicebus_trigger/function.json
tests/test_servicebus_functions.py

Add support for ServiceBus bindings

---

.flake8
.gitignore
appveyor.yml
azure/functions_worker/functions.py
azure/functions_worker/typing_inspect.py
setup.cfg
tests/broken_functions/bad_out_annotation/function.json
tests/broken_functions/bad_out_annotation/main.py
tests/test_broken_functions.py
tests/test_typing_inspect.py

Python 3.7 has had lots of changes in typing.py, so changes are
necessary in the function signature introspection code.
Issue: #166

Add support for Python 3.7

---

azure/functions_worker/bindings/http.py
setup.py
tests/http_functions/return_route_params/function.json
tests/http_functions/return_route_params/main.py
tests/test_http_functions.py
tests/test_types.py

Add HttpRequest.route_params property to access parsed route arguments

---

azure/functions_worker/dispatcher.py
tests/http_functions/unhandled_unserializable_error/function.json
tests/http_functions/unhandled_unserializable_error/main.py
tests/http_functions/unhandled_urllib_error/function.json
tests/http_functions/unhandled_urllib_error/main.py
tests/test_http_functions.py

Currently, if an unhandled exception in user function cannot be
serialized properly, the whole worker crashes.  Prevent that from ever
happening.
Fixes: #221

Prevent user exception serialization from failing

---

azure/__init__.py

azure-nspkg uses pkg_resources.declare_namespace which is incompatible
with PEP 420-style namespaces, which may lead to issues if other Azure
packages are installed in a different location.
Fixes: #268

Make azure namespace compatible with the style of azure-nspkg

---

azure/functions_worker/bindings/meta.py
tests/test_eventgrid_functions.py

It seems that Azure returns datetime with nanosecond precision, wheras
Python's datetime format only expects microseconds, so strip the extra
digits.
Fixes: #269

Fix parsing of datetime metadata with 7+ digits in second fraction

---

azure/functions_worker/dispatcher.py
azure/functions_worker/loader.py
tests/test_loader.py

Given the issues we've been getting for absolute imports over time, wanted to propose a change to the way we are currently handling namespaces for our Function App. Basically, the change involves removing `__azure__` as a top-level module and using the Function Application's directory name as a top-level module. Taking for example the following directory structure:
```
FunctionApp
Function1
__init__.py
func_module.py
HelperCode
__init__.py
helper_module.py
```
FunctionApp would be added as a top-level module instead of `__azure__`. We can then publish guidance to allow users to access absolute imports via the following syntaxes (assuming we are importing from `Function1.__init__.py`):
1. `from FunctionApp import HelperCode`
2. `from FunctionApp.HelperCode import helper_module`
Relative …

Add Function App directory as a top-level module

---

azure/functions_worker/bindings/http.py
tests/http_functions/return_request/main.py
tests/test_http_functions.py
tests/test_types.py

`RpcHttp.body` may be reformatted by the Functions Host, and as such,
may not be identical to the original body sent by the client.  This has
numerous problems (e.g invalid Content-Length etc.)  Sidestep the issue
by always using `RpcHttp.rawBody`.
See also: Azure/azure-functions-host#3875
Fixes: #260

Always use raw HTTP body

---

.ci/e2e/publish_tests/func_tests_core/customer_churn_app/build_native_deps_test.sh
.ci/e2e/publish_tests/func_tests_core/customer_churn_app/no_bundler_test.sh
.ci/e2e/publish_tests/func_tests_core/new_functionapp/build_native_deps_test.sh
.ci/e2e/publish_tests/func_tests_core/new_functionapp/no_bundler_test.sh
.ci/e2e/publish_tests/func_tests_core/new_functionapp/packapp_test.sh
.ci/e2e/publish_tests/publish_config.json
.ci/e2e/running-environments/Docker/test_runner.Dockerfile
azure-pipelines-nightly.yml

Three changes:
1. Add ability to override the func artifacts link in the CI
2. Add a 5 second delay between publish and trigger test. Because sometimes, the trigger test is too quick and it returns a 404.
3. Change line endings when copying scripts to a docker container.

Update CI tests for more control

---

azure-pipelines.yml
azure/functions_worker/bindings/blob.py
azure/functions_worker/bindings/cosmosdb.py
azure/functions_worker/bindings/eventgrid.py
azure/functions_worker/bindings/eventhub.py
azure/functions_worker/bindings/http.py
azure/functions_worker/bindings/meta.py
azure/functions_worker/bindings/queue.py
azure/functions_worker/bindings/servicebus.py
azure/functions_worker/bindings/timer.py
azure/functions_worker/functions.py
setup.py
tests/blob_functions/get_blob_as_bytes/function.json
tests/blob_functions/get_blob_as_bytes/main.py
tests/blob_functions/get_blob_as_str/function.json
tests/blob_functions/get_blob_as_str/main.py
tests/test_blob_functions.py

The generic binding infrastructure now allows annotating the function
argument as `str` or `bytes`.  This also adds support for `str` and
`bytes` binding for the blob functions.
Issue: #66.

Add support for raw data type bindings

---

azure/functions_worker/bindings/servicebus.py

Apparently, a Service Bus message may have no payload at the protocol
level, so the worker must account for that.
Fixes: #330

Handle cases where ServiceBus message has no payload

---

azure/functions_worker/dispatcher.py
azure/functions_worker/main.py
azure/functions_worker/testutils.py
tests/test-binding/foo/binding.py
tests/test-binding/functions/foo/function.json
tests/test-binding/functions/foo/main.py
tests/test-binding/setup.py
tests/test_loader.py

Use the setuptools entry_point infrastructure to automatically load
binding modules installed in the environment.
Fixes: #381.

Add support for out-of-tree bindings

---

tests/test_code_quality.py

CI is currently failing to start subprocess for mypy validation on 3.7.3 (it does not fail for 3.7.2). Skip if the failure occurs on 3.7.3 specifically.

Skip subprocess start failure for 3.7.3

---

azure/functions_worker/dispatcher.py
azure/functions_worker/testutils.py
tests/path_import/path_import.py
tests/path_import/test_path_import.sh
tests/test_rpc_messages.py

We need to clear `sys.path` cache to allow for reloading of modules from directories that are created after we start the host (i.e. during specialization).

Clear sys.path cache to import from new folders

---

azure/functions_worker/bindings/generic.py
tests/table_functions/table_in_binding/__init__.py
tests/table_functions/table_in_binding/function.json
tests/table_functions/table_out_binding/__init__.py
tests/table_functions/table_out_binding/function.json
tests/test_table_functions.py

Needed to enable https://github.com/Azure/azure-functions-python-worker/issues/448. Also applicable for any other binding that only supports `json`. The WebJobs SDK returns the table binding as a `json` (it cannot currently handle `string` or `binary`).

Allow json data type for generic table binding

---

azure/functions_worker/dispatcher.py
azure/functions_worker/tracing.py
tests/test_broken_functions.py

Fixes https://github.com/Azure/azure-functions-python-worker/issues/273
I implement an stackframe filter to suppress the error message from python "importlib":
1. The exception traceback will be extracted into a [StackSummary](https://docs.python.org/3/library/traceback.html#traceback.StackSummary)
2. Filter out unnecessary **<frozen importlib._bootstrap>** and **<frozen importlib._bootstrap_external>** according to @elprans cpython [reference](https://github.com/python/cpython/blob/0f4e8132820947d93eccf31b9e526b81c6ffa53d/Python/import.c#L1484)
3. Format the modified StackSummary
@maiqbal11

Add ModuleNotFound exception trace handler

---

pack/scripts/nix_deps.sh
pack/scripts/win_deps.ps1
pack/templates/nix_env_gen.yml
pack/templates/win_env_gen.yml

Make some additions to populating dependencies for tooling:
1. Add `__init__.py` to `azure` module to make it a namespace
2. Install `azure.functions` separately since we no longer include it as a worker dependency

Copy __init__.py for azure + install azure-functions

---

.ci/linux_devops_build.sh
azure-pipelines-e2e.yml
azure_functions_worker/bindings/datumdef.py
azure_functions_worker/constants.py
azure_functions_worker/dispatcher.py
setup.py
tests/endtoend/eventhub_batch_functions/eventhub_multiple/__init__.py
tests/endtoend/eventhub_batch_functions/eventhub_multiple/function.json
tests/endtoend/eventhub_batch_functions/eventhub_output_batch/__init__.py
tests/endtoend/eventhub_batch_functions/eventhub_output_batch/function.json
tests/endtoend/eventhub_batch_functions/get_eventhub_batch_triggered/__init__.py
tests/endtoend/eventhub_batch_functions/get_eventhub_batch_triggered/function.json
tests/endtoend/test_eventhub_batch_functions.py

Fixes https://github.com/Azure/azure-functions-python-worker/issues/411

Handle eventhub cardinality

---

azure-pipelines-e2e.yml
azure-pipelines.yml
azure_functions_worker/bindings/datumdef.py
azure_functions_worker/constants.py
azure_functions_worker/dispatcher.py
setup.py
tests/unittests/test_http_functions.py

Fix a bug https://github.com/Azure/azure-functions-python-worker/issues/519
1. Forbid host from sending duplicated body bytes data in [input_data, http.rawBody, trigger metadata].
2. Reconstruct http body from input_data.
3. Conversion by content type on [host](https://github.com/Azure/azure-functions-host/blob/96fe7f8fae29f859e4a7d3b40cc6d9c9c3f25d81/src/WebJobs.Script/OutOfProc/Rpc/MessageExtensions/RpcMessageConversionExtensions.cs#L235)
Discussed with @yojagad @pragnagopa

Pass bytes from invocation request metadata

---

tests/endtoend/eventhub_functions/eventhub_output/function.json
tests/endtoend/eventhub_functions/eventhub_trigger/function.json
tests/endtoend/test_eventhub_batch_functions.py
tests/endtoend/test_eventhub_functions.py

The send/receive event hub name should be the same when running e2e tests

Fix single event e2e tests in eventhub 

---

setup.py
tests/unittests/eventhub_mock_functions/eventhub_cardinality_many/__init__.py
tests/unittests/eventhub_mock_functions/eventhub_cardinality_many/function.json
tests/unittests/eventhub_mock_functions/eventhub_cardinality_many_bad_anno/__init__.py
tests/unittests/eventhub_mock_functions/eventhub_cardinality_many_bad_anno/function.json
tests/unittests/eventhub_mock_functions/eventhub_cardinality_one/__init__.py
tests/unittests/eventhub_mock_functions/eventhub_cardinality_one/function.json
tests/unittests/eventhub_mock_functions/eventhub_cardinality_one_bad_anno/__init__.py
tests/unittests/eventhub_mock_functions/eventhub_cardinality_one_bad_anno/function.json
tests/unittests/test_mock_eventhub_functions.py

https://github.com/Azure/azure-functions-python-library/pull/32
https://github.com/Azure/azure-functions-python-worker/issues/589
Add test scenarios for function using **cardinality=many** and **List[func.EventHubEvent]** as parameter type annotation

Update tests for azure-functions EventHub triggers

---

azure_functions_worker/protos/_src/README.md
azure_functions_worker/protos/_src/src/proto/FunctionRpc.proto
azure_functions_worker/protos/_src/src/proto/identity/ClaimsIdentityRpc.proto
setup.py

Needed to unblock https://github.com/Azure/azure-functions-python-worker/pull/554. Contains the same logic as https://github.com/Azure/azure-functions-python-worker/pull/528 which was reverted.

Update proto and add custom build steps

---

azure_functions_worker/bindings/__init__.py
azure_functions_worker/bindings/generic.py
azure_functions_worker/bindings/meta.py
azure_functions_worker/functions.py
setup.py

We want to enable durable functions in Azure Functions Python Worker.
Previously, we are blocked by the implicit return from the generic binding.
The solution in this PR is to define a rich binding for OrchestrationTrigger and allow implicit returns from the trigger.
https://github.com/Azure/azure-functions-python-library/pull/48
CI is failing due to dependencies on azure-functions-python-library
resolves: https://github.com/Azure/azure-functions-python-worker/issues/608
resolves: https://github.com/Azure/azure-functions-python-worker/issues/227
```javascript
// function.json
{
"scriptFile": "__init__.py",
"bindings": [
{
"name": "orctx",
"type": "orchestrationTrigger",
"direction": "in"
}
],
"disabled": false
}
```
```python
def main(orctx: func.OrchestrationContext):
orchestrate = …
```

Add durable functions support

---

tests/unittests/durable_functions/activity_trigger/function.json
tests/unittests/durable_functions/activity_trigger/main.py
tests/unittests/durable_functions/activity_trigger_no_anno/function.json
tests/unittests/durable_functions/activity_trigger_no_anno/main.py
tests/unittests/durable_functions/orchestration_trigger/function.json
tests/unittests/durable_functions/orchestration_trigger/main.py
tests/unittests/generic_functions/foobar_as_bytes_no_anno/function.json
tests/unittests/generic_functions/foobar_as_bytes_no_anno/main.py
tests/unittests/generic_functions/foobar_as_str_no_anno/function.json
tests/unittests/generic_functions/foobar_as_str_no_anno/main.py
tests/unittests/generic_functions/foobar_implicit_output/function.json
tests/unittests/generic_functions/foobar_implicit_output/main.py
tests/unittests/generic_functions/foobar_with_no_datatype/function.json
tests/unittests/generic_functions/foobar_with_no_datatype/main.py
tests/unittests/test_mock_durable_functions.py
tests/unittests/test_mock_generic_functions.py

Waiting for the durable functions library to be released for the full E2E test
1. Testing if the generic binding is working properly when
a. When function.json **dataType** is set to 'string' or 'bytes'
b. When function.json **type** has a generic binding name (does not match any of our built-in triggers)
c. When main.py has proper or no annotation type
2. Ensure durable function's **activityTrigger** and **orchestrationTrigger** does not fall into any of the generic bindings

Add unittests for generic bindings and durable functions

---

azure-pipelines.yml
azure_functions_worker/constants.py
azure_functions_worker/dispatcher.py
azure_functions_worker/main.py
azure_functions_worker/testutils.py
pack/scripts/win_deps.ps1
setup.py

To allow GRPC passing large message (e.g. large files) between worker and host.
Resolves: https://github.com/Azure/azure-functions-python-worker/issues/628
GRPC_ARG_MAX_RECEIVE_MESSAGE_LENGTH = -1 [docs](https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga813f94f9ac3174571dd712c96cdbbdc1)
GRPC_ARG_MAX_SEND_MESSAGE_LENGTH = -1 [docs](https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#gab4defdabac3610ef8a5946848592458c)
Fix build pipeline to support the latest host version

Drop GRPC message size limitation

---

azure_functions_worker/dispatcher.py
azure_functions_worker/logging.py
azure_functions_worker/protos/_src/src/proto/FunctionRpc.proto
azure_functions_worker/testutils.py
tests/unittests/test_http_functions.py
tests/unittests/test_mock_http_functions.py

resolves: https://github.com/Azure/azure-functions-python-worker/issues/635
resolves: https://github.com/Azure/azure-functions-python-worker/issues/634
resolves: https://github.com/Azure/azure-functions-python-worker/issues/580
1. Remove console logger when gRPC channel is established.
2. Use gRPC channel for every log entries once it is established.
3. Emit info "Function is async" if the entrypoint is marked with "async" keyword
4. Emit info "Function is sync" if the entrypoing is marked with "sync" keyword
5. Ensure all the worker logs are sent via **System** log category
1. Update protobuf file to v1.3.7

Improve logging in python worker

---

.flake8
.gitignore

Adding some mac-specific and pycharm-specific exceptions and `venv` to flake8.

Adding newer files into .gitignore and flake8 exceptions

---

azure_functions_worker/constants.py
azure_functions_worker/dispatcher.py
azure_functions_worker/loader.py
azure_functions_worker/utils/tracing.py
azure_functions_worker/utils/wrappers.py
tests/unittests/http_functions/missing_module/function.json
tests/unittests/http_functions/missing_module/main.py
tests/unittests/load_functions/brokenimplicit/function.json
tests/unittests/load_functions/brokenimplicit/main.py
tests/unittests/test_http_functions.py
tests/unittests/test_loader.py
tests/unittests/test_utilities.py

1. Attach troubleshooting URL in ImportError exception message.
2. Add a decorator in utilities **attach_message_to_exception**. This is for appending extra message on a specific exception generated from a specific functions.
3. Move tracing.py into utilities folder.
---

Attach troubleshooting guide for specific exception types

---

azure-pipelines.yml

Fixes Issue https://github.com/Azure/azure-functions-python-worker/issues/629
1. This PR fixes the release tag for Python Worker NuGet package release. Currently, the release tag does not match the host release tag [Release Examples](https://azfunc.visualstudio.com/Azure%20Functions%20Python/_release?_a=releases&view=mine&definitionId=1). As per Pragna, we should have a version schema of 2.x.x for v2 function app release and 3.x.x for v3 function app release.
2. After this PR being merged in, we should consider pushing each Python worker release align with the host version to a separate release branch `release/2.0.0` and `release/3.0.0`. This PR modifies the Azure Pipeline to generate the proper NuGet with correct version tags in it.
---

Fix Python Worker NuGet package to match host release version

---

azure_functions_worker/dispatcher.py

Fixes Issue https://github.com/Azure/azure-functions-python-worker/pull/632/files#diff-9a16b2f8bcbe955d554031aec6e96442R47
The `self._grpc_max_msg_len` is set to `None` due to passing None into `dispatcher.\_\_init\_\_()` method
---

Fix grpc size limitation

---

azure_functions_worker/dispatcher.py

Fixes the rest of the dispatcher not found issue.
Azure Functions Python Worker is using a **Protobuf** version of **3.12**
Customer could break our worker code by brining a **Protobuf** package **< 3.8.0**
**Issue Protobuf < 3.8.0**: https://github.com/protocolbuffers/protobuf/issues/6028
**Fix released Protobuf >= 3.8.0**: https://github.com/protocolbuffers/protobuf/commit/0de6577b7d5702a133f0eade4ddf6b94893e975a
We should use the backward compatible syntax in worker RpcLogCategory.
---

Make our worker code backward compatible with protobuf<3.8.0

---

setup.py

Bumping up the version to 1.1.6

---

azure_functions_worker/dispatcher.py
azure_functions_worker/testutils.py
python/prodV2/worker.py
python/prodV3/worker.config.json
python/prodV3/worker.py
setup.py
tests/endtoend/test_eventhub_batch_functions.py
tests/endtoend/test_eventhub_functions.py
tests/unittests/http_functions/debug_logging/main.py
tests/unittests/http_functions/debug_user_logging/main.py
tests/unittests/http_functions/sync_logging/main.py
tests/unittests/load_functions/pytest/__init__.py
tests/unittests/test_dispatcher.py
tests/unittests/test_http_functions.py
tests/unittests/test_loader.py
tests/unittests/test_mock_http_functions.py
tests/unittests/test_rpc_messages.py

* Fixing ''' to """ string for PyDocs
* Adding critical logs to hit that code path
* Marking some tests as flaky to allow it to be rerun.
* Adding some sleep when starting the test host/worker to allow it to start on mac.
* With `asycio.Task.creat_task()` now removed from Python 3.9, refactored it to work for 3.6-3.9.
* Bump `grpcio` and `grpcio-tools` from 1.26.0 to 1.32.0.
Fixes #742
---

Changes for 3.9 along with nit fixes

---

azure-pipelines.yml
pack/Microsoft.Azure.Functions.V3.PythonWorker.nuspec

Since GRPC does not have Windows Python 3.9 wheel, we should release the Azure Functions Python 3.9 preview without windows support.
https://github.com/grpc/grpc/issues/24344
---

Disable Python 3.9 build in Windows

---

azure_functions_worker/dispatcher.py
azure_functions_worker/testutils.py
tests/unittests/dispatcher_functions/show_context_async/__init__.py
tests/unittests/dispatcher_functions/show_context_async/function.json
tests/unittests/test_dispatcher.py

This is a fix to an issue where in Linux Consumption, the **PYTHON_THREADPOOL_THREAD_COUNT** app setting is not properly applied to an instance during specialization. This will make the Python worker in Linux Consumption ignore the app setting, making the maximum worker count always to 1. 
Miscellaneous:
1. I move `@patch` decorator in unittests to use **with patch()** syntax, since previously, it suppresses all assertion exceptions in **async** test cases.
2. Add a **reload_environment()** function in testutil to help us mock Linux Consumption specialization
---

Fix PYTHON_THREADPOOL_THREAD_COUNT not apply to Linux Conusmption

---

azure_functions_worker/dispatcher.py
azure_functions_worker/testutils.py
tests/unittests/test_http_functions.py

#745 introduced a regression as the host currently cannot handle apps with high rate of debug logs being sent to it. This PR reverts that change.
Fixes #
---

Reverting #745 to limit Debug logs

---

pack/scripts/nix_deps.sh

There's a size increase (~90MB) in grpcio library for Linux Python 3.6 worker which is caused by the manylinux2010 wheel is only recognized with pip >= 19.0.0.
I add the linux pip upgrade command in our linux package script.
Windows package script already has it.
---

Upgrade Linux pip before packaging worker

---

azure_functions_worker/dispatcher.py
azure_functions_worker/testutils.py
setup.py
tests/unittests/test_dispatcher.py

- Made the changes for Python 3.9 only.
- Added tests for verifying that the default is None only for Py3.9 and not for others.
---

Setting PTPTC to None for Py3.9 only

---

azure_functions_worker/dispatcher.py
azure_functions_worker/testutils.py
tests/unittests/test_dispatcher.py

Making the logs more actionable and usable for us. Now explicitly add function name in the log statement, along with the function id.
Also, when testing locally, it is useful to know the temporaryFile.name of the stdout file when starting the webworker.
Fixes #
---

Adding updates to the log messages

---

setup.py

Python SDK Version [1.6.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.6.0)

Update Python SDK Version to 1.6.0

---

azure_functions_worker/dispatcher.py

The WorkerStatusResponse fails to be read from the GRPC queue. https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/dispatcher.py#L639. gets no response, causing the host to wait for the response message back.
---

[HotFix] Disable Worker Status Report

---

azure_functions_worker/dispatcher.py
tests/endtoend/http_functions/default_template/__init__.py
tests/endtoend/http_functions/default_template/function.json
tests/endtoend/test_http_functions.py

Previously, due to an issue where the latest request id is not sent back to the host, the /admin/host/ping endpoint will always timeout with 408 response. This results in over-scaling behavior in Python function apps. We disabled the WorkerStatus to fix the regression.
In this PR, we're going to re-enable the worker status and fix the request_id that it now should propagate correctly. Adding more unittests and endtoend tests to prevent the issue from happening again.
1. Adding a new file to run endtoend tests for Http functions. This file is using the same testing infrastructure as unittest/test_http_functions.py but the scenarios are more focus on overall goodness of endtoend flow.
2. Re-enable the WorkerStatus request handler. Also add a test case in endtoend Http functions to ping the …

Re-enable WorkerStatus report in Worker

---

azure_functions_worker/logging.py
tests/unittests/log_filtering_functions/sdk_logging/__init__.py
tests/unittests/log_filtering_functions/sdk_logging/function.json
tests/unittests/log_filtering_functions/sdk_submodule_logging/__init__.py
tests/unittests/log_filtering_functions/sdk_submodule_logging/function.json
tests/unittests/test_log_filtering_functions.py
tests/unittests/test_logging.py
tests/unittests/test_mock_log_filtering_functions.py

Dependency https://github.com/Azure/azure-functions-python-library/pull/88
Fixes #https://github.com/Azure/azure-functions-python-worker/issues/840
From now on, we will treat 'azure.functions' namespace and its child namespace as system logs.
After merging this PR, we should be able to see the following log lines in our Kusto table:
1. Instantiating Azure Functions ASGI middleware.
2. Instantiating Azure Functions WSGI middleware.
This will help the PM team calculate the usage on WSGI/ASGI middlewares.
Core changes in `azure_functions_worker/logging.py`.
cc: @stefanushinardi @vrdmr @AnatoliB 
---

Categorize SDK logs as system logs

---

azure_functions_worker/loader.py
tests/unittests/load_functions/no_script_file/function.json
tests/unittests/load_functions/no_script_file/main.py
tests/unittests/test_loader.py

Some function.json files do not contain `scriptFile` property and that can cause the app to fail.
Fixes #
---

Add a default script_file to support function.json without scriptFile

---

azure_functions_worker/bindings/__init__.py
azure_functions_worker/bindings/context.py
azure_functions_worker/bindings/retrycontext.py
azure_functions_worker/bindings/rpcexception.py
azure_functions_worker/dispatcher.py
azure_functions_worker/protos/_src/src/proto/FunctionRpc.proto
setup.py
tests/unittests/http_functions/http_retries_exponential_backoff/function.json
tests/unittests/http_functions/http_retries_exponential_backoff/main.py
tests/unittests/http_functions/http_retries_fixed_delay/function.json
tests/unittests/http_functions/http_retries_fixed_delay/main.py
tests/unittests/test_http_functions.py

- Implemented retry context of python worker. 
Doc: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=python#retry-policies-preview
- Update protobuf file to include latest changed from https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto
Fixes #
---

Added Retry Context for python worker

---

setup.py

Python SDK Version [1.8.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.8.0)

Update Python SDK Version to 1.8.0

---

tests/unittests/test_enable_debug_logging_functions.py

Fixes #
Add comments to enable debug logging tests
Rename TestLogFilteringFunctions class
---

Add comments to enable debug logging tests

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/ut_ci_workflow.yml
README.md
azure_functions_worker/testutils.py
python/prodV4/worker.config.json
python/prodV4/worker.py
setup.py
tests/endtoend/eventhub_batch_functions/metadata_output_batch/__init__.py
tests/endtoend/eventhub_functions/metadata_output/__init__.py
tests/endtoend/test_linux_consumption.py
tests/unittests/resources/customer_func_path/common_module/__init__.py
tests/unittests/resources/customer_func_path/func_specific_module/__init__.py
tests/unittests/test_dispatcher.py
tests/unittests/test_rpc_messages.py
tests/unittests/test_utilities.py
tests/unittests/test_utilities_dependency.py

Enabling Python 3.10 CI and other changes

---

azure-pipelines.yml
pack/Microsoft.Azure.Functions.V2.PythonWorker.nuspec
pack/Microsoft.Azure.Functions.V3.PythonWorker.nuspec

Fix publish SBOM manifest with nuget package and changing Win to Linux for release pipeline

---

README.md
azure-pipelines.yml
pack/Microsoft.Azure.Functions.V4.PythonWorker.nuspec
pack/scripts/nix_deps.sh

Things changed in the PR:
- The nuspec files needed correction for Python 3.10 generation.
- Removed Tests section from `azure-pipelines.yml` as it wasn't required.
- Removed Python 3.6 generation and the V3 builds.
- Referencing the correct V4 nuspec.
- Also removed the need to install azure-functions in the `pack/scripts/nix_deps.sh` as we now made it as a required installation in `setup.py`.
---

Preparing nuspec file and pipeline changes for release

---

pack/templates/nix_env_gen.yml
pack/templates/win_env_gen.yml

This is to enable the Dependency Isolation feature, which requires `azure` to not be a module, but a namespace.
Fixes #
---

Removing __init__.py copy step in *_env_gen.yml files

---

azure_functions_worker/testutils.py

Fixes #
Add a check to read line from host_out only if stdout is readable in integration test.
---

Fix host_out readlines in test_utils

---

setup.py

Added an option in setup.py to use any branch from azure-functions-host
Usage
python setup.py webhost
python setup.py webhost --use-branch=dev
python setup.py webhost --use-branch=abc/branch
Fixes #
---
- [x ] I have read the [contribution guidelines](https://github.com/Azure/azure-functions-python-worker/blob/master/.github/CONTRIBUTING.md).

Added an option in setup.py to use any branch from azure-functions-host

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/perf-testing-setup.yml
.github/workflows/ut_ci_workflow.yml

Currently workflows are run using the host version latest tag. Updated workflows to use the host from dev branch to make sure the worker code is being tested against the latest dev branch
Fixes #
---

Updated workflows to use the host from dev branch

---

azure_functions_worker/testutils_lc.py
tests/endtoend/test_linux_consumption.py

Mounting the dev branch azure library in the docker image in the tests 
Fixes #
---

Update linux consumption tests to test with dev library

---

azure_functions_worker/loader.py
tests/unittests/test_http_functions.py
tests/unittests/test_loader.py

Adding recommendation to check the requirements.txt When user hits module not found error.
**Existing Error Message**: Troubleshooting Guide: {MODULE_NOT_FOUND_TS_URL}
**Updated Error Message:**  Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: {MODULE_NOT_FOUND_TS_URL}
Fixes #
---

updating the verbiage of 'ModuleNotFound' error.

---

.ci/perf_tests/dockerfiles/perf_tests.Dockerfile
.github/workflows/perf-testing-setup.yml

Fixing the Perf Testing workflow

---

azure_functions_worker/testutils_lc.py
tests/endtoend/test_dependency_isolation_functions.py
tests/endtoend/test_linux_consumption.py

Fixing dependency isolation tests for linux consumption by removing the __init__.py file from the azure directory. This change can be removed once worker 4.0.0 is released
Fixes #
---

Fixing dependency isolation tests for linux consumption

---

pack/Microsoft.Azure.Functions.V2.PythonWorker.nuspec
pack/Microsoft.Azure.Functions.V3.PythonWorker.nuspec

Fix build by fixing v2 and v3 nuspec
Fixes #
---

fix nuspec for v2 and v3

---

azure-pipelines.yml

Fixes #
Fix SBOM generation path for v3 release
---

update sbom path for release/3.1.3 branch

---

tests/endtoend/test_linux_consumption.py

Skipping linux consumption test for python 3.7  as this requires more investigation. 
Fixes #
---

Skipping linux consumption test for python 3.7 for V3

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/ut_ci_workflow.yml

Added a python -m while running pytest. This is to get tests pass in https://github.com/Azure/azure-functions-python-worker/pull/1017 
Fixes #
---

Added "python -m" while running pytest in CI workflows

---

setup.py

Python SDK Version [1.11.1](https://github.com/Azure/azure-functions-python-library/releases/tag/1.11.1)

Update Python SDK Version to 1.11.1

---

setup.py

Linux consumption tests are failing as module 'python-dateutil' not found error happening in https://github.com/Azure/azure-functions-python-worker/pull/1004. The cause is current mesh image is installing worker deps from released worker version instead of setup.py from local or pr branch. We will also update linux consumption test to use v4 images so this change will be taken into runtime image.
---

Mark python-dateutil as install required

---

setup.py

Python SDK Version [1.11.2](https://github.com/Azure/azure-functions-python-library/releases/tag/1.11.2)

Update Python SDK Version to 1.11.2

---

tests/endtoend/test_linux_consumption.py

unskip test_common_libraries for 3.7

---

tests/unittests/test_third_party_http_functions.py

label flaky httpfunction tests in thirdparty pystein http tests

---

azure_functions_worker/dispatcher.py
azure_functions_worker/logging.py
azure_functions_worker/main.py

Currently, the log messages do not contain any relevant traceback and exception details. Adding a new traceback info to be logged.
Fixes #
---

Logging traceback for fatal errors

---

setup.py

Python SDK Version [1.11.3b2](https://github.com/Azure/azure-functions-python-library/releases/tag/1.11.3b2)

Update Python SDK Version to 1.11.3b2

---

tests/endtoend/table_functions/table_functions_stein/function_app.py
tests/endtoend/table_functions/table_functions_stein/generic/function_app.py
tests/endtoend/test_table_functions.py

add E2E pystein and generic binding tests for table.

---

azure_functions_worker/dispatcher.py
azure_functions_worker/logging.py
azure_functions_worker/main.py
setup.py

Making a #1064 equivalent change for `v3.x` branch. 
Fixes #
---

Logging Tracebacks for Error Logger and SDK Update

---

tests/endtoend/eventhub_batch_functions/eventhub_batch_functions_stein/function_app.py
tests/endtoend/test_eventhub_batch_functions.py

add EventHubBatch E2E pystein tests.

---

tests/endtoend/blob_functions/blob_functions_stein/generic/function_app.py
tests/endtoend/test_blob_functions.py

add blob generic binding tests.

---

pack/templates/nix_env_gen.yml
pack/templates/win_env_gen.yml

Porting https://github.com/Azure/azure-functions-python-worker/pull/972 to v3
Fixes #
---

Removing __init__.py copy step in *_env_gen.yml files for v3

---

azure_functions_worker/bindings/datumdef.py
tests/unittests/test_datumref.py

cookies get key hotfix

---

setup.py

Python SDK Version [1.11.3b3](https://github.com/Azure/azure-functions-python-library/releases/tag/1.11.3b3)

Update Python SDK Version to 1.11.3b3

---

azure_functions_worker/_thirdparty/typing_inspect.py
tests/endtoend/blob_functions/blob_functions_stein/function_app.py
tests/endtoend/cosmosdb_functions/cosmosdb_functions_stein/function_app.py
tests/endtoend/eventgrid_functions/eventgrid_functions_stein/function_app.py
tests/endtoend/eventhub_batch_functions/eventhub_batch_functions_stein/function_app.py
tests/endtoend/eventhub_functions/eventhub_functions_stein/function_app.py
tests/endtoend/queue_functions/queue_functions_stein/function_app.py
tests/endtoend/servicebus_functions/servicebus_functions_stein/function_app.py
tests/endtoend/table_functions/table_functions_stein/function_app.py

Updated binding names for Stein tests
Fixes #
---

Updated stein tests in include new binding names

---

setup.py

Python SDK Version [1.11.3](https://github.com/Azure/azure-functions-python-library/releases/tag/1.11.3)

Update Python SDK Version to 1.11.3

---

.github/workflows/ut_ci_workflow.yml
azure-pipelines.yml
azure_functions_worker/functions.py
azure_functions_worker/testutils.py
setup.py
tests/endtoend/durable_functions/DurableFunctionsHttpStart/__init__.py
tests/endtoend/durable_functions/DurableFunctionsHttpStart/function.json
tests/endtoend/durable_functions/DurableFunctionsOrchestrator/__init__.py
tests/endtoend/durable_functions/DurableFunctionsOrchestrator/function.json
tests/endtoend/durable_functions/Hello/__init__.py
tests/endtoend/durable_functions/Hello/function.json
tests/endtoend/test_durable_functions.py

Fixed typo for setting implicit output binding
Fixes #
---

Bugfix for checking durable functions implicit output

---

azure_functions_worker/dispatcher.py
azure_functions_worker/loader.py
azure_functions_worker/utils/wrappers.py
setup.py
tests/endtoend/test_sql_functions.py

Added more debug logging for Pystein and module not found errors.
Fixes #
---

Improve indexing related logs

---

.ci/e2e_integration_test/pipeline.yml
.github/workflows/ci_e2e_workflow.yml
.github/workflows/codeql-analysis.yml
.github/workflows/perf-testing-setup.yml
.github/workflows/ut_ci_workflow.yml
azure_functions_worker/dispatcher.py
azure_functions_worker/testutils.py
tests/unittests/test_code_quality.py
tests/unittests/test_enable_debug_logging_functions.py
tests/unittests/test_utilities_dependency.py

Fixing extension bundle and test utils

---

azure_functions_worker/dispatcher.py
tests/endtoend/queue_functions/queue_functions_stein/generic/function_app.py
tests/endtoend/queue_functions/queue_trigger_message_return/function.json
tests/endtoend/queue_functions/queue_trigger_return/function.json
tests/endtoend/test_queue_functions.py

Fix test_queue_return flaky test and other nits

---

azure_functions_worker/logging.py
azure_functions_worker/utils/common.py
tests/unittests/test_logging.py

The signature for format_traceback for Python 3.10 has changed and is a breaking change. This PR addresses that breakage and also adds a test to validate it.
For Python 3.`0 - https://docs.python.org/3/library/traceback.html#traceback.print_exception
> Changed in version 3.10: The `etype` parameter has been renamed to `exc` and is now positional-only.
Fixes #
---

Fixing format_traceback's change of signature

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/ci_ut_workflow.yml
azure_functions_worker/logging.py
setup.py
tests/unittests/test_utilities.py

Adding Py3.11 for testing E2E and unit tests. 
Fixes #
---

Enabling Py3.11 for E2E and unit tests.

---

azure_functions_worker/dispatcher.py
azure_functions_worker/protos/__init__.py
azure_functions_worker/protos/_src/src/proto/FunctionRpc.proto
tests/unittests/test_dispatcher.py

Added worker metadata to WorkerInitResponse and FunctionEnvironmentReloadResponse
Fixes #1057
---

Added worker metadata to init and reload response

---

tests/utils/testutils.py

Updated testutils to use dedicated host
Fixes #
---

Updated testutils to use dedicated host

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/ci_ut_workflow.yml
tests/endtoend/test_blob_functions.py
tests/endtoend/test_blueprint_functions.py
tests/endtoend/test_cosmosdb_functions.py
tests/endtoend/test_dependency_isolation_functions.py
tests/endtoend/test_eventgrid_functions.py
tests/endtoend/test_eventhub_batch_functions.py
tests/endtoend/test_eventhub_functions.py
tests/endtoend/test_http_functions.py
tests/endtoend/test_table_functions.py
tests/unittests/test_enable_debug_logging_functions.py
tests/unittests/test_http_functions.py
tests/unittests/test_log_filtering_functions.py
tests/unittests/test_logging.py
tests/unittests/test_shared_memory_map.py
tests/unittests/test_third_party_http_functions.py

Running tests parallelly and increasing the verbosity of output
Fixes #1191 
---

Fixing E2E and UT flaky tests.

---

pack/scripts/nix_deps.sh
pack/scripts/win_deps.ps1
tests/utils/testutils_lc.py

DEPRECATION: azure-functions-worker is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
Fixes https://github.com/Azure/azure-functions-python-worker/issues/1219
---

Build fixes: Upgrading pip to 23.0 

---

setup.py
tests/endtoend/durable_functions/Hello/__init__.py
tests/endtoend/durable_functions/Hello/function.json
tests/endtoend/durable_functions/durable_functions_stein/function_app.py
tests/endtoend/test_durable_functions.py
tests/utils/testutils.py

Modified durable tests and added tests for pystein
Fixes #
---

Added durable functions stein tests

---

python/prodV4/worker.py

Added worker to pythonpath
Fixes #
---

Added worker to pythonpath

---

setup.py

Python SDK Version [1.14.1b3](https://github.com/Azure/azure-functions-python-library/releases/tag/1.14.1b3)

Update Python SDK Version to 1.14.1b3

---

.github/Scripts/e2e-tests.sh
.github/workflows/ci_e2e_workflow.yml

Fixes #1275 . This will fix the flaky PTPTC and FWPC e2e tests
---

Update e2e tests GH workflow to fix flaky tests.

---

azure-pipelines.yml
pack/Microsoft.Azure.Functions.V4.PythonWorker.nuspec
pack/scripts/mac_arm64_deps.sh
pack/templates/macos_64_env_gen.yml
python/prodV4/worker.config.json
setup.py

Updating the dependencies and build pipelines to support Arm64 macOS

---

setup.py

Python SDK Version [1.15.1b2](https://github.com/Azure/azure-functions-python-library/releases/tag/1.15.1b2)

Update Python SDK Version to 1.15.1b2

---

azure_functions_worker/functions.py
tests/unittests/test_functions_registry.py

Reverting route validation from the python worker. This will be adding in the library
Fixes #
---

Reverted route validation

---

setup.py

Python SDK Version [1.16.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.16.0)

Update Python SDK Version to 1.16.0

---

azure_functions_worker/main.py
tests/unittests/test_main.py

Updated python language worker to support handling new command line arguments with functions- prefix. Verified changes with Host debugging.
Fixes #1314 
---

Enable support for handling new command line arguments

---

setup.py

Python SDK Version [1.18.0b3](https://github.com/Azure/azure-functions-python-library/releases/tag/1.18.0b3)

Update Python SDK Version to 1.18.0b3

---

azure_functions_worker/loader.py
tests/unittests/test_loader.py

With the current release, python worker was failing with the following error
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: Failure Exception: AttributeError: 'Function' object has no attribute 'get_settings_dict' Stack:   File '/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py', line 345, in _handle__functions_metadata_request     fx_metadata_results = self.index_functions(function_path)   File '/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py', line 622, in index_functions     fx_metadata_results = loader.process_indexed_function(   File '/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/loader.py', line 109, in process_indexed_function     retry_protos = …

Attribute error fix for retry policy

---

azure_functions_worker/dispatcher.py
azure_functions_worker/logging.py
azure_functions_worker/utils/dependency.py
tests/consumption_tests/test_linux_consumption.py
tests/unittests/test_dispatcher.py

In linux consumption, when the host restarts the python worker due to any reason (timeout/OOM..), the host does not send an EnvironmentReload request since it assumes that the container has already been specialized. Due to this customer modules are not loaded and that causes the function app to fail with ModuleNotFound errors. 
Fix here is to load customer modules when the container is not in placeholder mode for linux consumption. 
Fixes #
---

Reload modules when not in placeholder mode

---

azure_functions_worker/constants.py
azure_functions_worker/dispatcher.py
python/prodV4/worker.py

Changes in worker and constants to fix "Customer packages not in sys path." warning log being hit.
Fixes #
---

fix for cust sys packages path

---

tests/unittests/test_dispatcher.py
tests/utils/testutils.py

Fixing the following UT errors
```python
FAILED tests/unittests/test_dispatcher.py::TestThreadPoolSettingsPython37::test_dispatcher_sync_threadpool_set_worker - AssertionError: 0 != 1 : stack_trace: "  File \"/home/runner/work/azure-functions-python-worker/azure-functions-python-worker/azure_functions_worker/dispatcher.py\", line 399, in _handle__function_load_request\n    self._functions.add_function(\n  File \"/home/runner/work/azure-functions-python-worker/azure-functions-python-worker/azure_functions_worker/functions.py\", line 338, in add_function\n    input_types, output_types = self.validate_function_params(params,\n  File \"/home/runner/work/azure-functions-python-worker/azure-functions-python-worker/azure_functions_worker/functions.py\", line 228, in validate_function_params\n …
```

Adding missing inits in tests to correct binding load errors

---

setup.py

Python SDK Version [1.18.0b4](https://github.com/Azure/azure-functions-python-library/releases/tag/1.18.0b4)

Update Python SDK Version to 1.18.0b4

---

.github/DISCUSSION_TEMPLATE/survey.yml

syntax changes to survey
Fixes #
---

syntax changes to survey

---

azure_functions_worker/bindings/generic.py
tests/unittests/test_mock_generic_functions.py

This reverts commit a981fcf788a0b57e4b4f679f7e1977ff11a1579b.
Fixes #
---

Revert "Enabling implicit output for generic bindings (#1348)"

---

azure_functions_worker/dispatcher.py
tests/unittests/test_dispatcher.py

Added a UTC timestamp to the received invocation logs. Edited tests to check for updated log format.
Fixes #1337
---

Add timestamp in the received invocation logs

---

azure_functions_worker/dispatcher.py
azure_functions_worker/utils/app_setting_manager.py
tests/unittests/test_app_setting_manager.py

Added space and delimiter for parsing. Logs now look like below:
Fixes https://github.com/Azure/azure-functions-pyfx-planning/issues/99
---

App Settings Logs formatting fixes

---

setup.py

Python SDK Version [1.18.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.18.0)

Update Python SDK Version to 1.18.0

---

azure_functions_worker/dispatcher.py
azure_functions_worker/loader.py
azure_functions_worker/utils/wrappers.py
tests/unittests/test_http_functions.py
tests/unittests/test_loader.py

Added console logging to show errors during function load & indexing

---

.github/workflows/ci_consumption_workflow.yml
.github/workflows/ci_docker_con_workflow.yml
.github/workflows/ci_docker_custom_workflow.yml
.github/workflows/ci_docker_ded_workflow.yml
.github/workflows/ci_e2e_workflow.yml
.github/workflows/ci_ut_workflow.yml
.github/workflows/codeql-analysis.yml
.github/workflows/linter.yml
.github/workflows/ogf_workflow.yml
.github/workflows/perf-testing-setup.yml

Support Speedscope format to profiling pipeline

---

setup.py

Python SDK Version [1.19.0b1](https://github.com/Azure/azure-functions-python-library/releases/tag/1.19.0b1)

Update Python SDK Version to 1.19.0b1

---

setup.py

Python SDK Version [1.19.0b2](https://github.com/Azure/azure-functions-python-library/releases/tag/1.19.0b2)

Update Python SDK Version to 1.19.0b2

---

azure_functions_worker/_thirdparty/typing_inspect.py
tests/unittests/test_typing_inspect.py

Previously, typing_inspect.py had a distinction between python versions <3.7 and >=3.7, and would change imports and return statements based on the python version. This refactoring changes this so that there are no longer special cases for python versions <3.7.
Fixes # https://github.com/Azure/azure-functions-pyfx-planning/issues/177
---

Refactoring typing_inspect.py

---

setup.py

I had moved dateutils to extra requires in the previous PR thinking it was only used in tests. Its actually used in datumdef.py.
Moving it back to install requires
Fixes #
---

Moved dateutil to install_requires
