Azure/azure-functions-python-worker

azure/worker/dispatcher.py

cc @asavaritayal @christopheranderson @elprans

Run synchronous functions in their own thread-pool

---

azure/functions/__init__.py
azure/functions/_abc.py
azure/functions/_http.py
azure/worker/rpc_types.py
azure/worker/tests/functions/return_http/function.json
azure/worker/tests/functions/return_http/main.py
azure/worker/tests/functions/return_http_404/function.json
azure/worker/tests/functions/return_http_404/main.py
azure/worker/tests/functions/return_http_redirect/function.json
azure/worker/tests/functions/return_http_redirect/main.py
azure/worker/tests/test_azure_functions.py
azure/worker/tests/test_functions.py

Implement HttpResponse support (see issue #4)

---

azure/functions/_abc.py
azure/worker/dispatcher.py
azure/worker/functions.py
azure/worker/rpc_types.py
azure/worker/tests/broken_functions/invalid_http_trigger_anno/function.json
azure/worker/tests/broken_functions/invalid_http_trigger_anno/main.py
azure/worker/tests/broken_functions/invalid_in_anno/function.json
azure/worker/tests/broken_functions/invalid_in_anno/main.py
azure/worker/tests/broken_functions/invalid_in_anno_non_type/function.json
azure/worker/tests/broken_functions/invalid_in_anno_non_type/main.py
azure/worker/tests/broken_functions/invalid_out_anno/function.json
azure/worker/tests/broken_functions/invalid_out_anno/main.py
azure/worker/tests/broken_functions/invalid_return_anno/function.json
azure/worker/tests/broken_functions/invalid_return_anno/main.py
azure/worker/tests/broken_functions/invalid_return_anno_non_type/function.json
azure/worker/tests/broken_functions/invalid_return_anno_non_type/main.py
azure/worker/tests/broken_functions/unsupported_bind_type/function.json
azure/worker/tests/broken_functions/unsupported_bind_type/main.py
azure/worker/tests/broken_functions/unsupported_ret_type/function.json
azure/worker/tests/broken_functions/unsupported_ret_type/main.py
azure/worker/tests/http_functions/return_bytes/function.json
azure/worker/tests/http_functions/return_bytes/main.py
azure/worker/tests/test_broken_functions.py
azure/worker/tests/test_http_functions.py

Closes issues #3 and #4.  We'll open new ones if we need to adjust the behaviour.

Implement strict type annotations checks and proper marshaling

---

azure/functions/_abc.py
azure/functions/_http.py
azure/worker/dispatcher.py
azure/worker/functions.py
azure/worker/loader.py
azure/worker/rpc_types.py
azure/worker/tests/test_code_quality.py
azure/worker/testutils.py
requirements-dev.txt
setup.cfg

Fix all outstanding errors reported by mypy
Fixes #29

Add mypy checking to the testsuite

---

.ci/travis_install.sh
DEVELOPMENT.md
appveyor.yml
requirements-dev.txt
requirements.txt
setup.py

Move dependencies to setup.py and make protobuf stub generation part of
setup.py build stage.

Simplify installation process

---

azure/worker/dispatcher.py
tests/http_functions/async_logging/main.py
tests/test_mock_http_functions.py

Fix logging.INFO level; pre-configure logging to log everything

---

setup.py

Stop claiming the root azure namespace

---

azure/worker/__init__.py
azure/worker/dispatcher.py
python/worker.py
setup.py

Add support for grpcMaxMessageLength command line argument

---

setup.py

Pin the dependencies and set the version to 2.0.0 alpha 2 dev

---

.flake8
azure/functions/__init__.py
azure/functions/_abc.py
azure/worker/bindings/__init__.py
azure/worker/bindings/eventhub.py
azure/worker/bindings/meta.py
azure/worker/testutils.py
setup.py
tests/eventhub_functions/eventhub_output/__init__.py
tests/eventhub_functions/eventhub_output/function.json
tests/eventhub_functions/eventhub_trigger/__init__.py
tests/eventhub_functions/eventhub_trigger/function.json
tests/eventhub_functions/get_eventhub_triggered/function.json
tests/eventhub_functions/get_eventhub_triggered/main.py
tests/eventhub_functions/host.json
tests/eventhub_functions/ping/README.md
tests/eventhub_functions/ping/function.json
tests/eventhub_functions/ping/main.py
tests/test_eventhub_functions.py

Add support for EventHub bindings

---

azure/worker/protos/_src/README.md
azure/worker/protos/_src/src/proto/FunctionRpc.proto
tests/test_http_functions.py

Updated subtree from https://github.com/azure/azure-functions-language-worker-protobuf.
Branch: dev.
Commit: aac95f236681ee11d81d220a88b3cbbd5470380a
Fixes: #123.

Update protobuf definitions

---

.ci/appveyor_setup_worker.py
python/worker.config.json
setup.py

Related issue: https://github.com/Azure/azure-functions-host/issues/3214

Update keys to camelCase and support list of extensions

---

azure/functions_worker/dispatcher.py
azure/functions_worker/loader.py
tests/load_functions/entrypoint/function.json
tests/load_functions/entrypoint/main.py
tests/test_loader.py

Add support for custom entry points

---

azure/functions_worker/bindings/meta.py
azure/functions_worker/bindings/queue.py
azure/functions_worker/functions.py
tests/queue_functions/put_queue_return_multiple/function.json
tests/queue_functions/put_queue_return_multiple/main.py
tests/queue_functions/queue_trigger_return_multiple/function.json
tests/queue_functions/queue_trigger_return_multiple/main.py
tests/test_queue_functions.py

Allow returning multiple messages in a queue binding

---

README.md

Updating doc pointers, to point to public documentation.

Updating doc pointers

---

python/worker.py

Restore compatibility with pre-b1 releases of worker in worker.py

---

.ci/devops_setup_worker.py
.ci/linux_devops_build.sh
.ci/linux_devops_dotnet.sh
.ci/linux_devops_tests.sh
.ci/linux_devops_tools.sh
.ci/win_devops_build.bat
.ci/win_devops_tests.bat
.ci/win_devops_tools.bat
azure-pipelines.yml
setup.py

Adding Azure DevOps CI

---

azure/functions_worker/bindings/eventgrid.py
azure/functions_worker/bindings/eventhub.py
azure/functions_worker/bindings/http.py
setup.py

The library repo now contains concrete implementations of the binding
types.

Move parts of the binding implementation to the library

---

azure/functions_worker/dispatcher.py
tests/queue_functions/put_queue_multiple_out/function.json
tests/queue_functions/put_queue_multiple_out/main.py
tests/test_queue_functions.py

Fix handling of multiple Out params

---

tests/test_eventgrid_functions.py

This is necessary to unblock #239.

Disable eventgrid tests for now

---

azure/functions_worker/bindings/eventhub.py
azure/functions_worker/testutils.py
setup.py
tests/eventhub_functions/eventhub_trigger/function.json
tests/eventhub_functions/eventhub_trigger_iot/__init__.py
tests/eventhub_functions/eventhub_trigger_iot/function.json
tests/eventhub_functions/get_eventhub_triggered/function.json
tests/test_eventhub_functions.py

Read device-id from EventHub event trigger metadata

---

setup.py

Update grpc to 1.20.1

---

.ci/e2e/publish_tests/dev_docker_setup/setup.sh
.ci/e2e/publish_tests/test_runners/run_all_parallel.sh
.ci/e2e/publish_tests/test_runners/run_all_serial.sh
.ci/e2e/publish_tests/test_runners/setup_test_environment.sh

Recent changes to our Dockerfiles caused nightly runs to fail.

Fix nightly tests Docker build

---

azure/functions_worker/dispatcher.py
azure/functions_worker/protos/__init__.py

Adding support to reload environment variables

---

pack/templates/nix_env_gen.yml
pack/templates/win_env_gen.yml

Fixes https://github.com/Azure/azure-functions-python-worker/issues/392

Remove grpc tools from package

---

azure-pipelines.yml
azure/functions_worker/dispatcher.py
setup.py
tests/test_rpc_messages.py

Fixes https://github.com/Azure/azure-functions-python-worker/issues/410

Clear environment before reloading

---

python/worker.py

Revert worker.py combatilibity fix (not needed anymore)

---

tests/test_rpc_messages.py

Avoid re-implementation of test root location.

Small refactor to reuse TESTS_ROOT

---

azure_functions_worker/dispatcher.py

Fixes https://github.com/Azure/azure-functions-python-worker/issues/529

Reload additional modules that user might need

---

azure-pipelines.yml

Removing beta tag from build name post-GA.

Remove beta tag for build name

---

.ci/linux_devops_tools.sh
azure-pipelines.yml
azure_functions_worker/testutils.py
setup.py

Maheer's credential expires, Azure DevOps pipeline fails to fetch GitHub repository.
I use this opportunity to clean up the build process.
1. Remove core tools dependencies
2. Fix an issue due to extension bundle is not resolved properly
3. Use dotnet to resolve functions extensions (provide more control on each extension version)

Fix azure pipelines

---

setup.py
tests/unittests/test_mock_eventhub_functions.py

Update azure-functions library to 1.1.0:
1. Includes a fix in iothub event metadata context
2. Includes a fix on cardinality when parsing events
3. Supports WSGI (no document yet)

Python worker version 1.0.4

---

setup.py

Introducing a new utils module in 1.0.4

[1.0.4] Adding utils as a submodule 

---

setup.py

Testing the new python functions library (1.2.1)
Fixes Issue # 
---

Bumping up the version to 1.1.1

---

azure-pipelines.yml

Fix an error in the elif statement
Fix an issue in nuspec_path variable reference
---

Fix syntax issue in azure-pipelinesyml

---

README.md

Update overview section in readme.md, changes include:
- Included Python 3.7 and 3.8 support
- Included release instructions in contribution guide 
---

Update overview section in readme.md

---

azure_functions_worker/dispatcher.py
azure_functions_worker/logging.py
azure_functions_worker/protos/_src/src/proto/FunctionRpc.proto
tests/unittests/test_mock_http_functions.py

This revert Improve logging in python worker.
**no currently running Dispatcher is found**
This is impacting several apps in CRIs we received.
The Python worker is not started correctly and log is not flowing back to the host.
---

[Revert] Improve logging in python worker

---

azure_functions_worker/constants.py
azure_functions_worker/dispatcher.py
azure_functions_worker/logging.py
tests/unittests/http_functions/hijack_current_event_loop/function.json
tests/unittests/http_functions/hijack_current_event_loop/main.py
tests/unittests/http_functions/print_logging/function.json
tests/unittests/http_functions/print_logging/main.py
tests/unittests/test_http_functions.py

Fixes https://github.com/Azure/azure-functions-python-worker/issues/714
- Ensure the messages in the gRPC async logging handler are flushed when encountering exceptions
- Ensure the messages in the sys.stdout are flushed before disabling console logging
- Redirect exception in AsyncLoggingHandler emit method into host console, since
- When encounter dispatcher exception, the logging will be switched to console log
- If not suppressing the exception in AsyncLoggingHandler emit method, it will trigger an infinite exception logging in gRPC channel.
- Never suppress error console logging handler, since it redirects log to stderr. This should be always enabled.
Tests:
1. Add a new test case for hijacking current event loop, since I see a lot of Azure Packages (`azure-eventhubs`, …

Fix no currently running Dispatcher is found issue

---

setup.py

Back merge to dev
---
- [] If applicable, the PR references the bug/issue that it fixes in the description.
- [] New Unit tests were added for the changes made and CI is passing.

Python worker version 1.1.3 (with azure-functions 1.3.0)

---

setup.py

Update Python worker version to 1.1.5 (with SDK version 1.3.1 https://github.com/Azure/azure-functions-python-library/releases/tag/1.3.1)
---

Update worker version to 1.1.5

---

.flake8
azure_functions_worker/dispatcher.py

Reduce logging for functions invocations to optimize for performance. This reduces the # of log statements from 3 to 1 (merging the first 2 log lines and removing the successful invocation)
---

Reduce logging for functions invocations

---

.ci/perf_tests/dockerfiles/perf_tests.Dockerfile
.ci/perf_tests/dockerfiles/perf_tests_3.6.Dockerfile
.ci/perf_tests/dockerfiles/perf_tests_3.7.Dockerfile
.ci/perf_tests/dockerfiles/perf_tests_3.9.Dockerfile
.ci/perf_tests/k6scripts/AsyncHttpTriggerCPUIntensive.js
.ci/perf_tests/k6scripts/AsyncHttpTriggerCPUIntensiveWithSleeps.js
.ci/perf_tests/k6scripts/AsyncHttpTriggerHelloWorld.js
.ci/perf_tests/k6scripts/AsyncHttpTriggerWithAsyncRequest.js
.ci/perf_tests/k6scripts/AsyncHttpTriggerWithSyncRequests.js
.ci/perf_tests/k6scripts/SyncHttpTriggerCPUIntensive.js
.ci/perf_tests/k6scripts/SyncHttpTriggerCPUIntensiveWithSleeps.js
.ci/perf_tests/k6scripts/SyncHttpTriggerHelloWorld.js
.ci/perf_tests/k6scripts/SyncHttpTriggerHtmlParser.js
.ci/perf_tests/k6scripts/SyncHttpTriggerWithMixWorkloads.js
.ci/perf_tests/k6scripts/SyncHttpTriggerWithSyncRequests.js
.ci/perf_tests/run-perftests.sh

This is the first of the two PRs for the new throughput testing workflow. The second PR will use the scripts from this PR.
---

Adding K6 throughput scripts

---

.github/workflows/perf-testing-setup.yml

For every CI run now, we'll find throughput numbers for some tests
A sample run: [GH Run 301048287](https://github.com/Azure/azure-functions-python-worker/actions/runs/301048287)
Fixes #
---

Adding a pipeline for getting throughput testing to CI

---

azure_functions_worker/_thirdparty/typing_inspect.py

Typing inspect issue: now the Python 3.8 _GenericAlias is diverged into two different path in Python 3.9, _GenericAlias and _SpecialGenericAlias. See https://bugs.python.org/issue40397
---

Fix typing inspect issue

---

.github/workflows/e2e_ci_workflow.yml
.github/workflows/perf-testing-setup.yml
.github/workflows/ut_ci_workflow.yml
azure-pipelines.yml
tests/endtoend/test_blob_functions.py

Third workflow for the repo - Replacing the AzureDevops for GHA.
Fixes #754
---

Creating a new E2E workflow on GHA

---

azure-pipelines.yml

Create a new pipeline for Python 3.9 build, the resources sit in SimpleBatch/AzureFunctionsPythonWorkerCILinuxDevOps.
- Azure Cosmos DB account (East US)
- Event Grid Topic (West US 2)
- Event Hubs Namespace (West US)
- Service Bus Namespace (West US)
- Storage Account (West US)
Fixes #754
---

Create a pipeline for Python 3.9 Worker Build

---

azure-pipelines.yml
setup.py
tests/endtoend/servicebus_functions/servicebus_trigger/__init__.py

Fix an E2E test issue where the servicebus fails to json.dump() a datetime object
---

Python Worker Release 1.1.7

---

.ci/linux_devops_build.sh
azure-pipelines.yml
pack/Microsoft.Azure.Functions.V3.PythonWorker.nuspec
setup.py

Since GRPC has recently release `1.33.2` version which contains windows-wheel in PyPi package, we should re-enable the windows Python 3.9 build in our Python Worker.
Original Thread: https://github.com/grpc/grpc/issues/24344
Generated Artifacts: https://azfunc.visualstudio.com/Azure%20Functions%20Python/_build/results?buildId=9493&view=artifacts&pathAsName=false&type=publishedArtifacts
---

Add support for Windows Python 3.9

---

.github/workflows/ogf_workflow.yml

- Adding new regions to overwatch
- Changing the schedule to 3 hours.
- Making Workflow Dispatch configurable.
Fixes #
---

Overwatch: Add new regions to test and other changes

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/perf-testing-setup.yml
.github/workflows/ut_ci_workflow.yml
azure-pipelines.yml
azure_functions_worker/testutils.py
setup.py
tests/endtoend/test_eventhub_batch_functions.py
tests/endtoend/test_eventhub_functions.py

1. Automatically fetch the latest v3 Functions Host for E2E test.
2. Compile v3 Functions Host on local environment.
3. Update on extensions.csproj to use the latest popular versions of extensions.
1. This setup.py only uses python builtin modules as it is a convention.
2. V3 function host no longer pass `sys` properties in bindings (checked by `git checkout dev; git diff v2.x`). Thus, I comment out the assertion in related eventhub tests.
---

Migrate E2E tests to V3 host

---

azure_functions_worker/dispatcher.py
azure_functions_worker/loader.py

Adding function name when loading and catching type error for the path error (as reported in #792).
Fixes #792
---

Logging improvements for better telemetry

---

setup.py

Added ptvsd module to be installed as part of dev requirements bundle to help with debugging
Adds `ptvsd` module to be installed as part of dev requirements bundle to help with debugging.
---

Added ptvsd to dev requirements

---

setup.py

Python SDK Version [1.7.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.7.0)

Update Python SDK Version to 1.7.0

---

.ci/e2e_integration_test/pipeline.yml
.ci/e2e_integration_test/start-e2e.ps1
.github/workflows/perf-testing-setup.yml

Test results are now available accessed from Azure DevOps
https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=13637&view=ms.vss-test-web.build-test-results-tab
cc: @Francisco-Gamino 
---

Generate E2E integration test report in Azure DevOps

---

setup.py

Python SDK Version [1.7.1](https://github.com/Azure/azure-functions-python-library/releases/tag/1.7.1)

Update Python SDK Version to 1.7.1

---

setup.py

Python SDK Version [1.7.2](https://github.com/Azure/azure-functions-python-library/releases/tag/1.7.2)

Update Python SDK Version to 1.7.2

---

tests/endtoend/test_dependency_functions.py
tests/unittests/test_extension.py
tests/unittests/test_shared_memory_manager.py
tests/unittests/test_utilities.py

Fixes E2E Integration Test https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=17962&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7dae026f-9e99-5d65-075e-3f7579577f94
This is due to the CI environment is not expect to use the default path.
/cc: @francisco-gamino
---

Skip paths resolution if in Integration Test CI

---

pack/templates/nix_env_gen.yml
pack/templates/win_env_gen.yml

Fix an issue where Python 3.9 worker fail to load azure. packages.
---
- [] If applicable, the PR references the bug/issue that it fixes in the description.
- [] New Unit tests were added for the changes made and CI is passing.

Ensure azure namespace is established in Python 3.9 in placeholder mode 

---

azure-pipelines.yml

Update logic to push the Python worker package to the AzureFunctionsPreRelease feed
---

Update logic to push the Python worker package to the AzureFunctionsPreRelease feed

---

azure-pipelines.yml

https://azfunc.visualstudio.com/AzurePythonFx/_workitems/edit/1412
As title is mentioned ..

add sbom generator task in the pipeline

---

azure-pipelines.yml

improve #918 by removing copy file task

remove copy file task

---

.github/workflows/linter.yml
azure-pipelines.yml

update pipeline's agent pool as per bi operation recommendation

---

setup.py

Python SDK Version [1.10.1](https://github.com/Azure/azure-functions-python-library/releases/tag/1.10.1)

Update Python SDK Version to 1.10.1

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/ut_ci_workflow.yml
README.md

Reformatted the README.md and removed 3.6 from CI

---

codecov.yml

ignore testutils files from code coverage

---

.github/workflows/codeql-analysis.yml

This PR introduces CodeQL to analyze and scan code regularly - 
Fixes #
---

Create codeql-analysis.yml for security checks

---

CODEOWNERS

As described in the title.
Fixes #
---

 Adding pdthummar to CodeOwners file

---

setup.py
tests/endtoend/test_cosmosdb_functions.py

Python SDK Version [1.11.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.11.0)

Update Python SDK Version to 1.11.0

---

README.md

updating readme with py3.10 coming soon

---

azure_functions_worker/testutils_lc.py
tests/endtoend/test_linux_consumption.py

Updated host version to 4 for consumption tests
Fixes #
---

Updated host version for consumption tests

---

tests/endtoend/test_linux_consumption.py

unskip lc tests

---

azure-pipelines.yml

The dev build was not correctly generating for v3.x versions.
Fixes #1044
---

Update azure-pipelines.yml to start generating correct build

---

setup.py

Reverts Azure/azure-functions-python-worker#1087

Revert "Update Python SDK Version to 1.11.3"

---

azure-pipelines.yml

Following https://github.com/actions/runner-images/issues/5583, macOS 10.15 is deprecated and moving to macOS 12.
---

Updating macOS image to macOS-12

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/ut_ci_workflow.yml
azure-pipelines.yml
azure_functions_worker/_thirdparty/typing_inspect.py

Updated branch name in az pipeline. Fixes https://github.com/Azure/azure-functions-python-worker/issues/1101
---

Azure pipeline fix for v3

---

setup.py

Python SDK Version [1.12.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.12.0)

Update Python SDK Version to 1.12.0

---

setup.py

Update Python SDK Version to 1.13.0b1

---

setup.py

Updated azure functions version to 1.13.2
Fixes #
---

Updated version to 1.13.2

---

setup.py

Updated grpcio, grpcio-tools and protobuf version for 3.11. support of MacOS arm64 is incldued in new version.
Fixes #
---

Updated grpcio, grpcio-tools and protobuf version for 3.11

---

setup.py

Updated sdk version to 1.13.3

---

.github/workflows/ci_consumption_workflow.yml
.github/workflows/ci_e2e_workflow.yml
.github/workflows/ci_ut_workflow.yml
setup.py

Python SDK Version [1.14.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.14.0)

Update Python SDK Version to 1.14.0

---

setup.py

Python SDK Version [1.14.1b2](https://github.com/Azure/azure-functions-python-library/releases/tag/1.14.1b2)

Update Python SDK Version to 1.14.1b2

---

setup.py

Python SDK Version [1.15.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.15.0)

Update Python SDK Version to 1.15.0

---

setup.py

Python SDK Version [1.15.1b1](https://github.com/Azure/azure-functions-python-library/releases/tag/1.15.1b1)

Update Python SDK Version to 1.15.1b1

---

setup.py

Fixing vulnerabilities by upgrading lib versions

---

setup.py

Update GRPCIO version for Python 3.8 and higher.

---

.github/DISCUSSION_TEMPLATE/survey.md

Added survey markdown file to repo to link in Discussions
---

Added survey markdown file to repo

---

.github/DISCUSSION_TEMPLATE/survey.yml

edit survey in YAML
Fixes #
---

survey edit per GH issue determining different syntax

---

.github/DISCUSSION_TEMPLATE/survey.yml

syntax changes to survey for GitHub Discussions

---

.github/DISCUSSION_TEMPLATE/survey.yml

This reverts commit c5b6ef035e22df81654151df5f85951e1957ebbb.
Fixes #
---

Add descriptors to survey in GitHub Discussions

---

.github/DISCUSSION_TEMPLATE/survey.yml

Fixed additional syntax for GitHub Discussions survey
Fixes #
---

Fixed additional syntax for GitHub Discussions survey

---

.github/workflows/ci_e2e_workflow.yml
.github/workflows/ci_ut_workflow.yml
.github/workflows/codeql-analysis.yml
tests/utils/testutils.py

Fix pipelines transient errors
